### ISSUE TITLE
Introduce caching in CI/CD process

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#28]
**Is your feature request related to a problem? Please describe.**
Implement caching in CI to speed up the build and CD process 

**Describe the solution you'd like**
Use `actions/cache@v3` to cache libs and skip yarn install if is not needed

**Example**
```
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build the project
         ...
```
