### ISSUE TITLE
string.charCodeAt is not a function

### ISSUE THREAD

**Issue by zJuuu** [akash-network/console-old#76]
**Describe the bug**
After creating a deployment with persistent storage i receive this error: string.charCodeAt is not a function caught in CustomApp.tsx#105 originated in @protobufjs/utf8/index.js#18.
This happens because it tries to use charCodeAt on a Uint8Array.

**To Reproduce**
1. Go to 'console.akash.network'
2. Click on 'import SDL'
3. Paste (Att. 1, See below)
4. Click save&close + create deployment + 'Next' after preflight check
5. See caught Error in console

**Expected behavior**
Create deployment for supplied sdl. (Att. 1)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Firefox
 - Version: 111.0

**Additional context**
I added a log to the utf8.length function and saw that it crashes after receiving a Uint8Array.
Please note that i removed the catch in CustomApp.tsx#105 and added a console.log to node_modules\@protobufjs\utf8\index.js#16 to receive this console output:
![grafik](https://user-images.githubusercontent.com/19760191/226410025-139a581a-d398-4e29-afbb-2c9c458badeb.png)

Att. 1:
```
---
version: '2.0'
services:
  node:
    image: 'ghcr.io/akash-network/cosmos-omnibus:v0.3.26-juno-v13.0.0'
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
    env:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/chain.json
      - GENESIS_URL=https://github.com/CosmosContracts/mainnet/raw/main/juno-1/genesis.json
      - SNAPSHOT_URL=https://snapshots.polkachu.com/snapshots/juno/juno_7469035.tar.lz4
      - JUNOD_IAVL_CACHE_SIZE=781250
      - JUNOD_IAVL_DISABLE_FASTNODE=false
      - ADDRBOOK_URL=https://snapshots.polkachu.com/addrbook/juno/addrbook.json
    params:
      storage:
        data:
          mount: /root/.juno
          readOnly: false
profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 32Gi
        storage:
          - size: 1Gi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta2
  placement:
    dcloud:
      pricing:
        node:
          denom: uakt
          amount: 1000
deployment:
  node:
    dcloud:
      profile: node
      count: 1
```
